pub mod catalog;
pub mod catalog_metadata;
pub mod conversion;
pub mod dependency;
pub mod error;
pub mod identifiers;
pub mod installer;
pub mod package;
pub mod package_ref;
pub mod raw;
pub mod validation;
pub mod version;

pub use catalog::{CatalogInstaller, CatalogPackage, RawCatalogInstaller, RawCatalogPackage};
pub use catalog_metadata::CatalogMetadata;
pub use dependency::Dependency;
pub use error::ModelError;
pub use identifiers::{BucketName, CatalogId, PackageName};
pub use installer::{Architecture, Installer, InstallerType};
pub use package::{Package, PackageKind, PackageSource};
pub use package_ref::{PackageId, PackageRef};
pub use raw::{RawFetchedInstaller, RawFetchedPackage, ScoopStreamEnvelope};
pub use validation::Validate;
pub use version::Version;
