name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/dependabot.yml'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: CI checks
    runs-on: windows-latest
    if: github.event_name != 'schedule'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: infra/go.mod
          cache: true
          cache-dependency-path: infra/go.sum

      - name: Setup Task
        uses: go-task/setup-task@v1
        with:
          version: 3.x

      - name: Install Lefthook
        uses: taiki-e/install-action@v2
        with:
          tool: lefthook

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest@0.9.122

      - name: Verify checks
        run: task ci:verify
